nameOverride: streams-console

namespace: 

hostName:

kafka:
  name: kafka-secure
  namespace: 
  listener: tls
  authentication:
    saslMechanism: SCRAM-SHA-512
  authorization: simple

argocd:
  syncwave:
    enabled: true
    console: "1"
